### ISSUE TITLE
Twitch throwing Error 5000 when attempting to watch a stream

### ISSUE THREAD

**Issue by ImperatorStorm** [ChoosenEye/Twitch-Adblock-Bugs#4]
To be precise, when attempting to watch a stream, instead of the stream playing normally, it instead throws a black screen stating "This video is unavailable. (Error #5000)."

**Comment by ChoosenEye** [comment]
normally Deletion of the Cookies from Twitch and a Refresh should be enough to clear this up, couldn't reproduce it for myself so i can't help here atm.

**Comment by ChoosenEye** [comment]
okay after a bit of debugging of the Server Code, there was a bug in the Auth System, which got fixed now. 

Otherwise Error 5000 would only happen if you not getting a valid Playlist for the Twitch Player from my Server.

TODO: Adding a loading on Twitch Servers directly if Playlist Requests returns no HTTP Error 200 or are smaller than 200 Bytes

**Comment by robjac** [comment]
Seems to be happening to me too. Is this not a public repo?  I don't see any source code

**Comment by ImperatorStorm** [comment]
> Seems to be happening to me too. Is this not a public repo? I don't see any source code

This is a bug tracker, the extension appears to not have any publicly-available source code

**Comment by durianbusuk** [comment]
> > Seems to be happening to me too. Is this not a public repo? I don't see any source code
> 
> This is a bug tracker, the extension appears to not have any publicly-available source code

It's probably a good thing; every other adblocking method with the source code available has been defeated by Twitch.

**Comment by ImperatorStorm** [comment]
as a proponent of FOSS, i disagree

**Comment by ImperatorStorm** [comment]
Haven't encountered any Error 5000s as of recent, closing
