### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jeovanny315** [ChoosenEye/Twitch-Adblock-Bugs#6]
![image](https://user-images.githubusercontent.com/79304571/111372496-f1169d80-8657-11eb-99a5-5a276ec78b56.png)

**Comment by ChoosenEye** [comment]
can you try it again?

**Comment by Kishin82** [comment]
Hello, still having ads

**Comment by ChoosenEye** [comment]
is your system time correct? 
do you see in the Dev Console of Firefox under Network a request to choosen.dev?

If Not you wont get a playlist from my server, so no Adblocking

**Comment by Kishin82** [comment]
Nevermind, right now it's working perfectly. I guess sometimes the extension didnt load well since i was on multiple streams ?
Its been 5 days and 0 ads.
Thanks!
