### ISSUE TITLE
showing stream as offline on firefox

### ISSUE THREAD

**Issue by Kingofgamesgx** [ChoosenEye/Twitch-Adblock-Bugs#7]
with Twitch Adblock enabled on firefox it displays a stream as offline

**Comment by Jorgi-1** [comment]
Working fine for me

**Comment by Kingofgamesgx** [comment]
> 
> Working fine for me


seems to be working now, earlier any stream i tried to go to with  Twitch Adblock enabled it showed as offline upon disabling and a page reload the stream was up but so where ads

**Comment by ChoosenEye** [comment]
if you getting Ads with the Extension Enabled or Stream is showing as Offline, you most times are not getting any Response from my Servers. 

currently there are extreme amounts of requests, i try my best to answer all so you can watch Twitch without interruptions.

**Comment by Kingofgamesgx** [comment]
> 
> 
> if you getting Ads with the Extension Enabled or Stream is showing as Offline, you most times are not getting any Response from my Servers.
> 
> currently there are extreme amounts of requests, i try my best to answer all so you can watch Twitch without interruptions.


thanks you for providing this for us, everything is working fine now
